# Use the official lightweight Alpine Linux image as the base image
FROM alpine:latest

# Set the working directory to /app
WORKDIR /app

# Copy the "hello.sh" script into the container at /app
COPY hello.sh .

# Make the script executable
RUN chmod +x hello.sh

# Define the command to run the script when the container starts
CMD ["./hello.sh"]